CREATE TABLE asesor (
    ci VARCHAR(500) PRIMARY KEY NOT NULL,
    fec_ingreso VARCHAR(500) NOT NULL,
    antiguedad INT NOT NULL,
    fec_mod TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    user_mod VARCHAR(500) NOT NULL,
    estado INT DEFAULT 1,
    FOREIGN KEY (ci) REFERENCES persona(ci) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE comision_pago (
    cod_contrato VARCHAR(100) NOT NULL,
    ci_asesor VARCHAR(500) NOT NULL,
    monto DECIMAL(10, 2) NOT NULL,
    moneda VARCHAR(500) NOT NULL,
    fec_pago VARCHAR(500) NOT NULL,
    tipo_pago VARCHAR(500) NOT NULL,
    fec_mod TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    user_mod VARCHAR(500) NOT NULL,
    estado INT DEFAULT 1,
    PRIMARY KEY (cod_contrato, ci_asesor),
    FOREIGN KEY (cod_contrato) REFERENCES contrato(cod_contrato) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (ci_asesor) REFERENCES asesor(ci) ON UPDATE CASCADE ON DELETE CASCADE
);