CREATE TABLE depositante (
    ci VARCHAR(500) PRIMARY KEY NOT NULL,
    ocupacion VARCHAR(500) NOT NULL,
    sector VARCHAR(500) NOT NULL,
    nota VARCHAR(500) NOT NULL,
    fec_mod TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    user_mod VARCHAR(500) NOT NULL,
    estado INT DEFAULT 1,
    FOREIGN KEY (ci) REFERENCES persona(ci) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE contacto (
    ci VARCHAR(500) PRIMARY KEY NOT NULL,
    nombre_contacto VARCHAR(500) NOT NULL,
    celular_contacto VARCHAR(500) NOT NULL,
    fec_mod TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    user_mod VARCHAR(500) NOT NULL,
    FOREIGN KEY (ci) REFERENCES depositante(ci) ON UPDATE CASCADE ON DELETE CASCADE
);