CREATE TABLE persona (
    ci VARCHAR(500) PRIMARY KEY NOT NULL,
    exp VARCHAR(500) NOT NULL,
    nombres VARCHAR(500) NOT NULL,
    apellidos VARCHAR(500) NOT NULL,
    code VARCHAR(500) NOT NULL,
    celular VARCHAR(500) NOT NULL,
    nacionalidad VARCHAR(500) NOT NULL,
    fec_nac VARCHAR(500) NOT NULL,
    direccion VARCHAR(500) NOT NULL,
    descripcion VARCHAR(500) DEFAULT '',
    fec_mod TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    user_mod VARCHAR(500) NOT NULL
);

CREATE TABLE cuenta_bancaria (
    ci VARCHAR(500) PRIMARY KEY NOT NULL,
    banco VARCHAR(500) NOT NULL,
    nro_cuenta VARCHAR(500) NOT NULL,
    moneda VARCHAR(500) NOT NULL,
    tipo_cuenta VARCHAR(500) NOT NULL,
    fec_mod TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    user_mod VARCHAR(500) NOT NULL,
    FOREIGN KEY (ci) REFERENCES persona(ci) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE beneficiario (
    ci VARCHAR(500) PRIMARY KEY NOT NULL,
    nombre_beneficiario VARCHAR(500) NOT NULL,
    celular_beneficiario VARCHAR(500) NOT NULL,
    ci_beneficiario VARCHAR(500) NOT NULL,
    fec_mod TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    user_mod VARCHAR(500) NOT NULL,
    FOREIGN KEY (ci) REFERENCES persona(ci) ON UPDATE CASCADE ON DELETE CASCADE
);