CREATE TABLE rol (
    rol VARCHAR(500) PRIMARY KEY NOT NULL,
    autorizacion INT NOT NULL
);

CREATE TABLE usuario (
    ci VARCHAR(500) PRIMARY KEY NOT NULL,
    usuario VARCHAR(500) NOT NULL UNIQUE,
    rol VARCHAR(500) NOT NULL,
    autorizacion INT NOT NULL,
    fec_mod TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    user_mod VARCHAR(500) NOT NULL,
    estado INT DEFAULT 1,
    FOREIGN KEY (ci) REFERENCES persona(ci) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE auth (
    usuario VARCHAR(500) PRIMARY KEY NOT NULL,
    password VARCHAR(500) NOT NULL,
    pregunta VARCHAR(500) NOT NULL,
    respuesta VARCHAR(500) NOT NULL,
    fec_mod TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    user_mod VARCHAR(500) NOT NULL,
    FOREIGN KEY (usuario) REFERENCES usuario(usuario) ON UPDATE CASCADE ON DELETE CASCADE
);